/* Autogenerated shim: import the existing UI module from project root. */
// We import the file contents by re-exporting from a dynamic import if available.
// For simplicity and to avoid duplicating ~2k lines, we import the built module at dev time.
// If this fails due to path restrictions, copy index.tsx into this file.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
export * from '../../index';
// @ts-ignore
import '../../index';

